RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = no
OLED_DRIVER_ENABLE = yes
EXTRAKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
VIA_ENABLE = yes
# using elite-c controllers
BOOTLOADER = qmk-dfu